### ISSUE TITLE
Add examples for config scrapers 

### ISSUE THREAD

**Issue by moshloop** [flanksource/config-db#219]
## Fixtures

- [x] aws
- [x] azure
- [x] azuredevops
- [x] file
- [x] githubactions
- [x] kubernetes
- [x] kubernetesfile
- [x] sql
- [x] trivy

## Deployed

- [x] aws
- [x] azure
- [x] githubactions
- [x] kubernetes
- [x] trivy
- [x] azuredevops
- [x] kubernetesfile
- [x] file
- [x] sql

**Comment by adityathebe** [comment]
We have the fixtures but let's deploy some of them

**Comment by adityathebe** [comment]
https://github.com/flanksource/aws-sandbox/pull/143

**Comment by adityathebe** [comment]
All fixtures have been added and they have also been deployed
