### ISSUE TITLE
Service account needs pods/exec permissions

### ISSUE THREAD

**Issue by moshloop** [flanksource/config-db#259]
failed to execute command: pods "postgresql-0" is forbidden: User "system:serviceaccount:default:config-db-sa" cannot create resource "pods/exec" in API group "" in the namespace "default", stdout= stderr=

**Comment by dabasvibhor** [comment]
@moshloop 

1. Will it be okay to restrict the role rule with a `resourceNames` field and the value set to `exec` ? 
2. Which verbs would be needed out of `create,delete,deletecollection,get,list,patch,update,watch` ?

**Comment by moshloop** [comment]
@dabasvibhor - I think it just needs pods/exec here: https://github.com/flanksource/config-db/blob/main/chart/templates/serviceaccount.yaml
