### ISSUE TITLE
Transform - Remove fields

### ISSUE THREAD

**Issue by moshloop** [flanksource/config-db#3]
There are some fields that are recorded in config items that change very often and would pollute the change history and/or cause excessive updates to config items.

```
transform:
   - removeFields:
         - EC2Instace.block_device_mappings.AttachTime
         - EC2Instance.PatchState.OperationEndTime
         - EC2Instance.PatchState.OperationStartTime
```

**Comment by vgtom** [comment]
Hi Moshe...Vinu Thomas here...I dont see the EC2Instance.PatchState.OperationStartTime in the code base...

For EC2Instance.PatchState.OperationEndTime and EC2Instace.block_device_mappings.AttachTime, you want me to remove it from the database...right??

**Comment by vgtom** [comment]
Also I am running the scrapper with samples/scrapper.yaml

aws:
 - region: ap-south-1
   compliance: true
   patch_states: true
   patch_details: true
   inventory: true

But I guess i need an AWS IAM role specified in the config file...right? Can you attach the same?
