### ISSUE TITLE
Newly detected items should be undeleted 

### ISSUE THREAD

**Issue by moshloop** [flanksource/config-db#311]
e.g. https://incident-commander.demo.aws.flanksource.com/catalog/018894c8-9c17-1004-8428-a628b8e45f24 is shown as deleted, even though is currently being returned with no deletion timestamp

+ we probably need to be more defensive when considering items for deletion / cleanup e..g empty lists due to a temporary issue

**Comment by yashmehrotra** [comment]
Strategy:
Track reason why deleted:
    1. Missing
    2. Picking up deleted from a status field
    3. Deleted from an event

When we scrape, if the reason is missing or status field returns undeleted, then undelete it from database

**Comment by yashmehrotra** [comment]
Fixed via #314
