### ISSUE TITLE
HTTP Scraper

### ISSUE THREAD

**Issue by moshloop** [flanksource/config-db#44]
Create a new scraper, similar to the file scraper (which uses go-getter) except the http scraper uses HTTPConnection / client with support for

* Authentication / Oauth / Tls
* Headers
* Method
* Body

https://github.com/flanksource/canary-checker/blob/master/checks/http.go can. be used as a base

```yaml
http
  - type: $.response.type # $.response is body of the http response
    id: $.headers.id # headers is a http headers from the response
    url: https://domain/requires_auth
    method: POST
    body: |+
         {"hello": "world"}
    authentication:
         username:
            value: dummy
        password:
            secretMapRef:
                name: auth
                key: password

**Comment by mrinalwahal** [comment]
Hey, @moshloop!

Can you please provide a description of what this issue is about? So that we can contribute and solve this.

The same goes for most of the issues labelled "good-first-issue."

Thanks! :)

**Comment by moshloop** [comment]
@mrinalwahal  see updated
