### ISSUE TITLE
Consume events duplicate config_items 

### ISSUE THREAD

**Issue by moshloop** [flanksource/config-db#631]
failed to save 1 results: failed to create config items: ERROR: duplicate key value violates unique constraint "config_items_pkey" (SQLSTATE 23505)

**Comment by adityathebe** [comment]
This was last observed in `docker.io/flanksource/config-db:v0.0.315`.

Will monitor for a few more days to see if this happens again.

**Comment by adityathebe** [comment]
don't see this anymore.
