### ISSUE TITLE
Exclusion by label not working 

### ISSUE THREAD

**Issue by moshloop** [flanksource/config-db#767]
The pod created by the pod canaries (httpbin) should be ignored, but they are not

**Comment by adityathebe** [comment]
@moshloop I am not seeing any exclusion annotations in the httpbin pods (checked aws sandbox)

**Comment by moshloop** [comment]
@adityathebe It should be based on

https://github.com/flanksource/mission-control-registry/blob/main/charts/kubernetes/values.yaml#L88-L94

**Comment by adityathebe** [comment]
> @adityathebe It should be based on
> 
> https://github.com/flanksource/mission-control-registry/blob/main/charts/kubernetes/values.yaml#L88-L94

Ah. I was looking for `config-db.flanksource.com/ignore` annotation.
