### ISSUE TITLE
Fingerprint - Cache only id's

### ISSUE THREAD

**Issue by moshloop** [flanksource/config-db#822]
I don't think we want to cache the entire change - just the change id - for memory and stale data - reasons.  If we do find a dupe then we should be doing `Update .. Set count = count + 1, ....`

_Originally posted by @moshloop in https://github.com/flanksource/config-db/pull/813#discussion_r1713253341_

**Comment by adityathebe** [comment]
https://github.com/flanksource/config-db/pull/848
