### ISSUE TITLE
 ERROR: ON CONFLICT DO UPDATE command cannot affect row a second time 

### ISSUE THREAD

**Issue by moshloop** [flanksource/config-db#893]
failed to save results: failed to create config changes: ERROR: ON CONFLICT DO UPDATE command cannot affect row a second time (SQLSTATE 21000): hint: Ensure that no rows proposed for insertion within the same command have duplicate constrained values.

**Comment by adityathebe** [comment]
not seeing this anymore since we added the trigger on config changes
